<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Hexashop - Empower Women</title>


    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="assets/css/font-awesome.css">

    <link rel="stylesheet" href="assets/css/HowiyyaShop.css">

    <link rel="stylesheet" href="assets/css/owl-carousel.css">

    <link rel="stylesheet" href="assets/css/lightbox.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="assets/css/custom.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!--

    TemplateMo 571 Hexashop

    https://templatemo.com/tm-571-hexashop

    -->
</head>

<body>
<?php
include 'header.php';
?>


<!-- ***** Header Area End ***** -->

<!-- ***** Main Banner Area Start ***** -->
<div class="page-heading empW-page-heading" id="top">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="inner-content">
                    <h2 style="">Empowering Women</h2>
                    <span>PALESTINIAN WOMEN ARE THE SUPER WOMEN</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Main Banner Area End ***** -->

<!-- ***** About Area Starts ***** -->
<div class="empW">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="left-image">
                    <img src="assets/images/emw1.JPG" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="right-content">
                    <h4>Empower Women</h4>
                    <span style="font-size: 18px">
                           HOWIYYA began with one goal in mind, empowering women in the West Bank. If not for the group of
                        local mothers who approached us, voicing their desire for work, HOWIYYA would not exist.
                        This is why our mission to empower women will always be central in everything we do.
                        </span>

                </div>
            </div>
        </div>
        <div class="row" style="padding-top: 20px ">
            <div class="col-lg-6">
                <div class="right-content">

                        <span style="font-size: 18px">
                        In the West Bank, unemployment rates for women are extremely high,
                            affecting over 60% of this demographic. Many of these women have historically
                            earned little to no income to help support their families. HOWIYYA has helped to ease
                            the burden for many of these women. Each of our artisans earns a living wage, well above the local minimum.


                        </span>


                </div>
            </div>
            <div class="col-lg-6">
                <div class="left-image">
                    <img src="assets/images/wp2.JPG" alt="">

                </div>
            </div>
        </div>

    </div>
</div>
<!-- ***** About Area Ends ***** -->
<div class="container" style="padding-top: 20px  font-size: 14px;  color: #aaaaaa;font-weight: 500;display: block;  margin-top: 25px;">
         <span style="font-size: 18px">
                      With the income generated by working with us, our artisans are able to provide
                            for themselves and their families. We ensure that every woman at HOWIYYA knows her worth and
                            feels confident to share her opinions. The income and community we’ve created has given our artisans
                            the stability needed to create larger dreams for themselves and our organization.
             There are numerous other barriers for Palestinian women trying to attain work,
             including the constraints of society and geography. It is not common for women in the area to have reliable
             means of transportation, meaning daily commutes can be an obstacle. We allow all of our artisans the choice of
             working from home, where they can work and care for their families simultaneously.
             <br>
             <br>

             HOWIYYA delivers materials to these women so they have the freedom to earn income and fulfill personal responsibilities.
             Our commitment and dedication to women empowerment has been recognized both locally and internationally.
             The supportive nature of our organization has become well known in local communities,
             where new applications from women looking to join HOWIYYA are being received each week.
             In addition to local recognition, our work has even been endorsed by the Fair Trade Federation.
             Our Fair Trade certification is a reflection of our promise to provide fair wages to our employees,
             implement sustainable manufacturing practices, and support marginalized communities.

         </span>
</div>
<div style="position: relative; text-align: center;">
    <img src="assets/images/wp3.JPG" alt="" style="display: block; margin: 0 auto; height: 200px ">
</div>

<div class="container" style="padding-top: 20px  font-size: 14px;  color: #aaaaaa;font-weight: 500;display: block;  margin-top: 25px;">
         <span style="font-size: 18px">

             HOWIYYA delivers materials to these women so they have the freedom to earn income and fulfill personal responsibilities.
             Our commitment and dedication to women empowerment has been recognized both locally and internationally.
             The supportive nature of our organization has become well known in local communities,
             where new applications from women looking to join HOWIYYA are being received each week.
             In addition to local recognition, our work has even been endorsed by the Fair Trade Federation.
             Our Fair Trade certification is a reflection of our promise to provide fair wages to our employees,
             implement sustainable manufacturing practices, and support marginalized communities.

         </span>
</div>



<!-- ***** Footer Start ***** -->
<?php
include 'footer.php';
?>
<!-- jQuery -->
<script src="assets/js/jquery-2.1.0.min.js"></script>

<!-- Bootstrap -->
<script src="assets/js/popper.js"></script>
<script src="assets/js/bootstrap.min.js"></script>

<!-- Plugins -->
<script src="assets/js/owl-carousel.js"></script>
<script src="assets/js/accordions.js"></script>
<script src="assets/js/datepicker.js"></script>
<script src="assets/js/scrollreveal.min.js"></script>
<script src="assets/js/waypoints.min.js"></script>
<script src="assets/js/jquery.counterup.min.js"></script>
<script src="assets/js/imgfix.min.js"></script>
<script src="assets/js/slick.js"></script>
<script src="assets/js/lightbox.js"></script>
<script src="assets/js/isotope.js"></script>

<!-- Global Init -->
<script src="assets/js/custom.js"></script>

<script>

    $(function() {
        var selectedClass = "";
        $("p").click(function(){
            selectedClass = $(this).attr("data-rel");
            $("#portfolio").fadeTo(50, 0.1);
            $("#portfolio div").not("."+selectedClass).fadeOut();
            setTimeout(function() {
                $("."+selectedClass).fadeIn();
                $("#portfolio").fadeTo(50, 1);
            }, 500);

        });
    });

</script>

</body>

</html>
